### ISSUE TITLE
Add possibility to create automatically a connection from a YAML file

### ISSUE THREAD

**Issue by Dynnammo** [Quentinchampenois/airbyte-ruby#1]
## Context
As a data analyst, I often have sources that have the same tables that I want to synchronize, with a specific sync mode that isn't the default one

## Frustration
When setting up the connection manually, I have to select manually all the relevant tables (without forgetting one or adding an irrelevant one), and precise the sync mode for each. It's far from error-proof and redundant.

## Solution
Using the the specified endpoint : https://reference.airbyte.com/reference/createconnection and a manually filled `connection.yaml` file, create the connection with all its information.

the `connection.yaml` could be the following:
```yaml
sourceId: 1239874892-12341234-123412
destinationId: 1234-12341243-1234124
sync_time : 0 0 12 * * ?
timezone : Europe/Paris
destination_namespace : default
destination_prefix: null
streams:
    - myFirstTable
    - mySecondTable
    - myThirdTable
 sync_mode: full_refresh_overwrite
```
